### ISSUE TITLE
Consensus type

### ISSUE THREAD

**Issue by livelybug** [octopus-network/substrate-ibc#18]
Currently, substrate-ibc only supports grandpa type, while ibc-rs only supports tendermint type.

**Comment by en** [comment]
There have been some changes since moving to the new solution of integrating ibc-rs into substrate-ibc:

1. With ibc-rs, substrate-ibc will have an out-of-box tendermint client
2. The old grandpa client is no longer valid and will be replaced by a BEEFY (a secondary protocol of grandpa) client. We might keep calling it grandpa client.

The rust BEEFY client is under development and will eventually be merged into ibc-rs.
On the cosmos-sdk side, the [substrate-light-client](https://github.com/ChorusOne/substrate-light-client) that ChorusOne implemented would no longer be applicable and a new implementation would be required.
